
export const mockAiResponses = {
  step1: "Vielen Dank für deine Offenheit. Es ist total verständlich, dass du dich in dieser Situation überfordert fühlst. Viele Menschen in ähnlichen Positionen erleben das. Was ich aber schon jetzt heraushöre, ist dein starker Wille, etwas zu verändern und deine Fähigkeit, die Situation klar zu beschreiben. Das ist eine fantastische Ausgangslage!",
  step2: "Basierend auf deinen Schilderungen habe ich deine Situation zusammengefasst:\n\n**IST-Situation:** Ich fühle mich in meiner aktuellen Rolle fremdbestimmt und reagiere oft nur noch auf die Anforderungen anderer. Das führt dazu, dass ich abends erschöpft bin und das Gefühl habe, nicht voranzukommen.\n\n**SOLL-Situation:** Ich möchte meine Aufgaben proaktiv gestalten und klare Prioritäten setzen. Ich will am Ende des Tages das Gefühl haben, das Wichtigste geschafft zu haben und wieder mehr Energie für mich zu haben.\n\nStimmt das so für dich?",
  step3: "Das Bild des Bergsteigers auf dem Gipfel in Verbindung mit deinem Ziel, deine Aufgaben proaktiv zu gestalten, ist sehr kraftvoll. Es scheint, als ob 'Ankommen' und 'Übersicht gewinnen' für dich zentrale emotionale Anker sind. Das Bild symbolisiert nicht nur den erreichten Erfolg, sondern auch den anstrengenden, aber lohnenden Weg dorthin. Die Klarheit und Weite auf dem Gipfel stehen im starken Kontrast zu deinem Gefühl der Fremdbestimmung.",
  step4: "Um das Bild noch klarer zu machen, lass uns prüfen, ob ein Aspekt fehlt. Oft liegen solche Herausforderungen in einem von drei Bereichen. Wo erkennst du dich am ehesten wieder?\n\n1.  **Können:** Fehlt dir vielleicht eine spezifische Fähigkeit oder Methode (z.B. eine Zeitmanagement-Technik)?\n2.  **Wollen:** Gibt es einen unbewussten inneren Anteil, der sich gegen die Veränderung sträubt, vielleicht aus Angst vor mehr Verantwortung?\n3.  **Dürfen:** Gibt es äußere Umstände oder Personen in deinem Umfeld, die dich daran hindern, proaktiver zu handeln?",
  step5: "Danke, das hilft sehr. Lass uns nun die Schlüsselsituation genauer betrachten. Du beschreibst, dass das Gefühl der Überforderung am stärksten ist, wenn morgens unerwartete, dringende Anfragen per E-Mail kommen. Der Schlüsselaffekt, der dabei mitschwingt, scheint eine Mischung aus **Ohnmacht** (die Kontrolle zu verlieren) und **Frustration** (die eigenen Pläne durchkreuzt zu sehen) zu sein. Könnte das zutreffen?",
  step7: "Analyse des Interviews mit der 'Bremse':\n\n**Zusätzliche Argumente der Bremse:**\n- 'Wenn ich mehr Verantwortung übernehme, habe ich auch mehr Angriffsfläche für Kritik.'\n- 'Bisher hat es doch auch immer irgendwie geklappt, warum also das Risiko eingehen?'\n\n**Ranking der Ausbalancierungsdimensionen:**\n1.  **Wollen (Primär):** Ein starker innerer Anteil fürchtet die Konsequenzen des Erfolgs (Neid, mehr Arbeit).\n2.  **Dürfen (Sekundär):** Das Verhalten des Teamchefs scheint passives Verhalten zu belohnen.\n\n**Kausaler Zusammenhang:** Die Angst vor den negativen Seiten des Erfolgs ('Wollen') wird durch das Umfeld ('Dürfen') verstärkt, was die aktuelle Problematik stabilisiert.",
  step8: "Vorschlag für ein übergeordnetes Lern- und Entwicklungsziel:\n\n'Ich lerne, meine berufliche Wirksamkeit selbstbewusst zu gestalten und anzunehmen, indem ich proaktiv handle und meine Erfolge als positiven Beitrag für mich und das Unternehmen wertschätze.'",
  step10: "Analyse der Widerstände:\n\nBasierend auf dem Interview mit den Widerstands-Anteilen lassen sich folgende Muster und Glaubenssätze erkennen:\n\n- **Perfektionismus:** 'Wenn ich etwas nicht 120% perfekt machen kann, fange ich es lieber gar nicht erst an.' (Regel der Realitätswahrnehmung)\n- **Anerkennungsstreben:** 'Ich muss es allen recht machen, um gemocht zu werden.' (Handlungsstrategie)\n- **Zurückhaltung:** 'Wenn ich meine Meinung sage, könnte das zu Konflikten führen, die ich nicht aushalte.' (Willensbildung)",
  step11: "Hier ist ein Entwurf für deine persönliche Erfolgsimagination:\n\n'Ich stehe auf dem Gipfel, genau wie auf dem Bild, das ich gewählt habe. Die Luft ist klar, und ich blicke weit über die Landschaft unter mir. Dieses Gefühl von Übersicht und Ruhe ist jetzt mein ständiger Begleiter im Arbeitsalltag. An die Stelle der Ohnmacht ist ein Gefühl von **souveräner Gelassenheit** getreten. Ich sehe neue Aufgaben nicht mehr als Bedrohung, sondern als interessante Herausforderungen, die ich mit Freude annehme. Ich gestalte meinen Tag und bin stolz auf das, was ich bewirke.'",
  step12: "Projektplan basierend auf der Erfolgsimagination:\n\n**Projekt: Souveräne Gelassenheit im Job**\n\n1.  **Meilenstein 1 (Woche 1-2): Proaktive Tagesplanung**\n    - Aktion: Jeden Morgen 15 Min. blocken, um die Top 3 Prioritäten des Tages festzulegen.\n    - Messung: Tägliches Journal: Wie oft habe ich mich an meine Prioritäten gehalten?\n\n2.  **Meilenstein 2 (Woche 3-4): Grenzen setzen**\n    - Aktion: Mindestens 2x pro Woche eine nicht dringende Anfrage höflich ablehnen oder delegieren.\n    - Messung: Notizen über die Situationen und das Ergebnis.\n\n**Mentaltraining:** Täglich morgens 3 Minuten die Erfolgsimagination visualisieren.",
};

export const getStepDetails = (currentStep) => {
    const details = {
        1: { title: 'Schritt 1: Erste Problem- & Zielbeschreibung', description: 'Rapportaufbau und erste Problembeschreibung durch den Coachee.'},
        2: { title: 'Schritt 2: Erweiterte Problem- & Zielbeschreibung', description: 'Vertiefung durch zusätzliche Informationen zur Ist- und Soll-Situation.'},
        3: { title: 'Schritt 3: Immersive Bildarbeit', description: 'Emotionale Visualisierung des Ziels mithilfe von Bildern und anschließende KI-Analyse.'},
        4: { title: 'Schritt 4: Überprüfung auf fehlende Informationen', description: 'Klärung offener Punkte mittels KI-generierter Fragen zu "Ausbalancierungsproblemen".'},
        5: { title: 'Schritt 5: Bestimmung von Schlüsselsituation & Schlüsselaffekt', description: 'Identifikation der Situationen, in denen das Problem am stärksten auftritt, und des zugrundeliegenden Affekts.'},
        6: { title: 'Schritt 6: Tiefenpsychologisches Interview mit Avataren', description: 'Intuitive Identifizierung von Persönlichkeitsanteilen mittels Aufstellungsarbeit.' },
        7: { title: 'Schritt 7: KI-Auswertung des Interviews', description: 'Die KI analysiert das Transkript, um Argumente, Dimensionen und Zusammenhänge aufzudecken.' },
        8: { title: 'Schritt 8: Identifikation des übergeordneten Ziels', description: 'Entwicklung eines übergeordneten Lern- und Entwicklungsziels ("Ziel hinter dem Ziel").' },
        9: { title: 'Schritt 9: Antizipieren von Umsetzungswiderständen', description: 'Erneute Aufstellungsarbeit zur Visualisierung von inneren Widerständen und Gewohnheiten.' },
        10: { title: 'Schritt 10: KI-Analyse der Widerstände', description: 'Die KI analysiert die Regeln und Glaubenssätze hinter den geäußerten Widerständen.' },
        11: { title: 'Schritt 11: Entwicklung einer Erfolgsimagination', description: 'Erstellung einer lebhaften mentalen Vorwegnahme des Erfolgs zur Umtrainierung des Schlüsselaffekts.' },
        12: { title: 'Schritt 12: Konkretisierung und Projektplan', description: 'Übertragung der Imagination in einen konkreten Projektplan für die praktische Umsetzung.' },
    };
    return details[currentStep] || {};
}
